# Generated by Django 3.0.2 on 2020-01-17 12:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_book', models.CharField(choices=[('COM', 'Computer'), ('NAT', 'Natual_Science'), ('ECO', 'ECONOMY'), ('HIS', 'History')], default=True, max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('published_date', models.DateField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bookstore.Book')),
            ],
        ),
    ]
