# Generated by Django 3.0.2 on 2020-01-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='type_big',
            field=models.CharField(choices=[('COM', 'Computer'), ('NAT', 'Natual_Science'), ('ECO', 'ECONOMY'), ('HIS', 'History')], default=True, max_length=10),
        ),
        migrations.AddField(
            model_name='book',
            name='type_detail',
            field=models.CharField(choices=[('NOR', 'Normal'), ('TCP', 'TCP/IP'), ('SEC', 'Security')], default=True, max_length=10),
        ),
        migrations.AddField(
            model_name='book',
            name='type_small',
            field=models.CharField(choices=[('GAM', 'Game'), ('GRA', 'Graphic'), ('NET', 'Network'), ('MOB', 'Mobile')], default=True, max_length=10),
        ),
    ]
