# Generated by Django 3.0.2 on 2020-01-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_auto_20200118_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='type2',
            field=models.CharField(choices=[('GAM', 'Game')], default=True, max_length=10),
        ),
    ]
